version: '3.8'

services:

  sonarqube:
    image: sonarqube:10.4-community
    container_name: sonarqube
    depends_on:
      - sonarqube_database
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_database:5432/sonarqube
      SONAR_JDBC_USERNAME: "sonaruser"
      SONAR_JDBC_PASSWORD: "changeme"

  sonarqube_database:
    image: postgres:alpine3.19
    container_name: sonarqube_database
    environment:
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_USER: "sonaruser"
      POSTGRES_DB: "sonarqube"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432"

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
